/// Flutter icons CustomAppIcon
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomAppIcon
///      fonts:
///       - asset: fonts/CustomAppIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomAppIcon {
  CustomAppIcon._();

  static const _kFontFam = 'CustomAppIcon';
  static const String? _kFontPkg = null;

  static const IconData insurance_card = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doctor_male = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lab = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alertfilled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clinicmedical = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
